version: "3.9"
services:

  api:
    container_name: itech_api
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./api:/var/www/api

  apache:
    container_name: itech_apache
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    volumes:
      - ./api:/var/www/api
      - .docker/apache/conf/site.conf:/etc/apache2/sites-enabled/site.conf
    ports:
      - 80:80
    links:
      - api
